# create an array of 10

In [2]:

import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# create an array of 10 fives

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# creat an array of the integer from 10 to 50

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# create an array of all the even integer from 10 t0 50

In [7]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

# create a 3x3 matrix with values ranging from 0 to 8

In [9]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# create a 3x3 identity matrix

In [10]:
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# unse numpy to generate an array of 25 random numbers sampled from a standard normal distribution




In [11]:
np.random.randn(25)

array([-0.61429204,  2.06522243,  1.38955551,  0.82687905, -0.80147123,
       -0.841267  , -0.80792954,  0.04063845,  1.57991876, -0.02336319,
       -0.1562332 ,  0.70904432, -0.19789087, -0.39579118, -0.2069057 ,
        1.95465559,  0.93147426,  0.22669639,  0.84915324, -0.18991859,
       -1.22774052, -0.46550216, -0.65970255,  1.40804972, -0.01527521])

# create a array of 20 linearly spaced points between 0 and 1

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])