# Numpy getting started


In [4]:
# !pip install numpy
print(np.__version__)

1.23.5


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
print(arr.shape)
print(arr.ndim)
print(arr.dtype.name)
print(arr.itemsize)
print(arr.size)
print(type(arr))

(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>


### Linspace

In [13]:
#linspace is used to create an array with evenly spaced elements
np.linspace(0,10,30).reshape(2,5,3)

array([[[ 0.        ,  0.34482759,  0.68965517],
        [ 1.03448276,  1.37931034,  1.72413793],
        [ 2.06896552,  2.4137931 ,  2.75862069],
        [ 3.10344828,  3.44827586,  3.79310345],
        [ 4.13793103,  4.48275862,  4.82758621]],

       [[ 5.17241379,  5.51724138,  5.86206897],
        [ 6.20689655,  6.55172414,  6.89655172],
        [ 7.24137931,  7.5862069 ,  7.93103448],
        [ 8.27586207,  8.62068966,  8.96551724],
        [ 9.31034483,  9.65517241, 10.        ]]])

### np complex numbers

In [14]:

np.array([1,2,3,4,5],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [15]:
np.zeros((2,3,4),dtype=np.int64)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)

### various dtype of numpy are
### bool_, int_, intc, intp, int8, int16, int32, int64, uint8, uint16, uint32, uint64, float_, float16, float32, float64, complex_, complex64, complex128

## generating random array

In [17]:
a=np.ones(3,dtype=np.int32)

In [28]:
ran_arr=np.random.rand(2,3)
ran_arr=np.random.randint(2,34,12)
ran_arr
print(ran_arr)

[ 2 22 24  7 25  7  5 24 25  8 21 32]


In [30]:
ran_arr.max()
ran_arr.min()
ran_arr.sum()

#ran_arr argmax is used to find the index of the maximum value
ran_arr.argmax()

#ran_arr argmin is used to find the index of the minimum value
ran_arr.argmin()

11

In [34]:
a=np.random.rand(3,3,5)
print(a)

[[[0.58249271 0.96444058 0.00660863 0.82848417 0.66831128]
  [0.68104331 0.11770565 0.79622654 0.73659188 0.98322358]
  [0.12273261 0.73698039 0.37860561 0.01593674 0.3816661 ]]

 [[0.12688721 0.9971921  0.59778357 0.17978124 0.94006256]
  [0.39454582 0.92159314 0.546407   0.17255762 0.62582758]
  [0.71172632 0.69025642 0.15168614 0.90652585 0.87194489]]

 [[0.36552766 0.5759716  0.78300841 0.66919585 0.57250385]
  [0.55322368 0.08112182 0.15829419 0.8711385  0.06273406]
  [0.55568077 0.57049432 0.20514801 0.27497702 0.71882539]]]


# indexing slicing iteration

In [37]:
a=np.arange(0,30).reshape(5,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
